import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "rgb(var(--ax-on-tertiary-fixed-rgb) / <alpha-value>)",
        "surface-dim": "rgb(var(--ax-surface-dim-rgb) / <alpha-value>)",
        error: "rgb(var(--ax-error-rgb) / <alpha-value>)",
        "primary-fixed": "rgb(var(--ax-primary-fixed-rgb) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--ax-on-surface-variant-rgb) / <alpha-value>)",
        "on-secondary-container": "rgb(var(--ax-on-secondary-container-rgb) / <alpha-value>)",
        "on-secondary-fixed-variant": "rgb(var(--ax-on-secondary-fixed-variant-rgb) / <alpha-value>)",
        "inverse-primary": "rgb(var(--ax-inverse-primary-rgb) / <alpha-value>)",
        "on-error-container": "rgb(var(--ax-on-error-container-rgb) / <alpha-value>)",
        background: "rgb(var(--ax-background-rgb) / <alpha-value>)",
        "outline-variant": "rgb(var(--ax-outline-variant-rgb) / <alpha-value>)",
        "tertiary-fixed-dim": "rgb(var(--ax-tertiary-fixed-dim-rgb) / <alpha-value>)",
        outline: "rgb(var(--ax-outline-rgb) / <alpha-value>)",
        "surface-tint": "rgb(var(--ax-surface-tint-rgb) / <alpha-value>)",
        "on-primary-fixed-variant": "rgb(var(--ax-on-primary-fixed-variant-rgb) / <alpha-value>)",
        "secondary-fixed": "rgb(var(--ax-secondary-fixed-rgb) / <alpha-value>)",
        surface: "rgb(var(--ax-surface-rgb) / <alpha-value>)",
        primary: "rgb(var(--ax-primary-rgb) / <alpha-value>)",
        "inverse-on-surface": "rgb(var(--ax-inverse-on-surface-rgb) / <alpha-value>)",
        "on-secondary-fixed": "rgb(var(--ax-on-secondary-fixed-rgb) / <alpha-value>)",
        "on-error": "rgb(var(--ax-on-error-rgb) / <alpha-value>)",
        "tertiary-container": "rgb(var(--ax-tertiary-container-rgb) / <alpha-value>)",
        "on-tertiary": "rgb(var(--ax-on-tertiary-rgb) / <alpha-value>)",
        "on-primary-container": "rgb(var(--ax-on-primary-container-rgb) / <alpha-value>)",
        "on-tertiary-container": "rgb(var(--ax-on-tertiary-container-rgb) / <alpha-value>)",
        "on-secondary": "rgb(var(--ax-on-secondary-rgb) / <alpha-value>)",
        "surface-container": "rgb(var(--ax-surface-container-rgb) / <alpha-value>)",
        "surface-container-lowest": "rgb(var(--ax-surface-lowest-rgb) / <alpha-value>)",
        "surface-container-high": "rgb(var(--ax-surface-high-rgb) / <alpha-value>)",
        "secondary-container": "rgb(var(--ax-secondary-container-rgb) / <alpha-value>)",
        "primary-container": "rgb(var(--ax-primary-container-rgb) / <alpha-value>)",
        "on-surface": "rgb(var(--ax-on-surface-rgb) / <alpha-value>)",
        "error-container": "rgb(var(--ax-error-container-rgb) / <alpha-value>)",
        "inverse-surface": "rgb(var(--ax-inverse-surface-rgb) / <alpha-value>)",
        "on-primary-fixed": "rgb(var(--ax-on-primary-fixed-rgb) / <alpha-value>)",
        tertiary: "rgb(var(--ax-tertiary-rgb) / <alpha-value>)",
        "on-background": "rgb(var(--ax-on-background-rgb) / <alpha-value>)",
        "surface-variant": "rgb(var(--ax-surface-variant-rgb) / <alpha-value>)",
        "primary-fixed-dim": "rgb(var(--ax-primary-fixed-dim-rgb) / <alpha-value>)",
        "tertiary-fixed": "rgb(var(--ax-tertiary-fixed-rgb) / <alpha-value>)",
        "surface-container-low": "rgb(var(--ax-surface-low-rgb) / <alpha-value>)",
        secondary: "rgb(var(--ax-secondary-rgb) / <alpha-value>)",
        "on-primary": "rgb(var(--ax-on-primary-rgb) / <alpha-value>)",
        "surface-container-highest": "rgb(var(--ax-surface-highest-rgb) / <alpha-value>)",
        "surface-bright": "rgb(var(--ax-surface-bright-rgb) / <alpha-value>)",
        "on-tertiary-fixed-variant": "rgb(var(--ax-on-tertiary-fixed-variant-rgb) / <alpha-value>)",
        "secondary-fixed-dim": "rgb(var(--ax-secondary-fixed-dim-rgb) / <alpha-value>)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-manrope)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-inter)"],
      },
      boxShadow: {
        panel: "0 20px 48px rgba(6, 10, 22, 0.48)",
      },
    },
  },
  plugins: [],
};

export default config;
