import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./app/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#311300",
        "surface-dim": "#0c1321",
        error: "#ffb4ab",
        "primary-fixed": "#d7e3ff",
        "on-surface-variant": "#c1c6d5",
        "on-secondary-container": "#a1b9e8",
        "on-secondary-fixed-variant": "#2f476f",
        "inverse-primary": "#005cba",
        "on-error-container": "#ffdad6",
        background: "#0c1321",
        "outline-variant": "#414753",
        "tertiary-fixed-dim": "#ffb688",
        outline: "#8b919f",
        "surface-tint": "#abc7ff",
        "on-primary-fixed-variant": "#00458e",
        "secondary-fixed": "#d7e3ff",
        surface: "#0c1321",
        primary: "#abc7ff",
        "inverse-on-surface": "#2a3040",
        "on-secondary-fixed": "#001b3f",
        "on-error": "#690005",
        "tertiary-container": "#e07316",
        "on-tertiary": "#512400",
        "on-primary-container": "#002959",
        "on-tertiary-container": "#471f00",
        "on-secondary": "#163057",
        "surface-container": "#19202e",
        "surface-container-lowest": "#070e1c",
        "surface-container-high": "#232a39",
        "secondary-container": "#314972",
        "primary-container": "#448ffd",
        "on-surface": "#dce2f6",
        "error-container": "#93000a",
        "inverse-surface": "#dce2f6",
        "on-primary-fixed": "#001b3f",
        tertiary: "#ffb688",
        "on-background": "#dce2f6",
        "surface-variant": "#2e3544",
        "primary-fixed-dim": "#abc7ff",
        "tertiary-fixed": "#ffdbc7",
        "surface-container-low": "#151b2a",
        secondary: "#afc7f7",
        "on-primary": "#002f65",
        "surface-container-highest": "#2e3544",
        "surface-bright": "#323949",
        "on-tertiary-fixed-variant": "#733600",
        "secondary-fixed-dim": "#afc7f7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-manrope)"],
        body: ["var(--font-inter)"],
        label: ["var(--font-inter)"],
      },
      boxShadow: {
        panel: "0 20px 48px rgba(6, 10, 22, 0.48)",
      },
    },
  },
  plugins: [],
};

export default config;
